# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-07 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='words',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words_searched', models.CharField(max_length=50)),
            ],
        ),
    ]
